micronaut:
  application:
    name: auth
  ssl:
    enabled: true
    buildSelfSigned: true
datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER}
    schema-generate: CREATE_DROP
    dialect: ${JDBC_DIALECT}
flyway:
  datasources:
    default:
      enabled: true