micronaut:
  application:
    name: auth
  server:
    cors:
      enabled: true
  netty:
    event-loops:
      other:
        num-threads: 10
        prefer-native-transport: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
        generator:
          refresh-token:
            secret: ${JWT_REFRESH_SIGNATURE_SECRET}
    endpoints:
      oauth:
        ## micronaut-security: security-jwt TokenRefreshRequest dto missing constructor,
        ## creating own controller: fixed in 4.0.0
        enabled: false
---
r2dbc:
  datasources:
    default:
      url: ${AUTH_R2DBC_URL}
      username: ${AUTH_JDBC_USERNAME}
      password: ${AUTH_JDBC_PASSWORD}
      dialect: ${AUTH_JDBC_DIALECT}
#    url: ${BACKUP_AUTH_R2DBC_URL} # backup
datasources:
  default:
    url: ${AUTH_JDBC_URL}
    username: ${AUTH_JDBC_USERNAME}
    password: ${AUTH_JDBC_PASSWORD}
    dialect: ${AUTH_JDBC_DIALECT}
#    url: ${BACKUP_AUTH_JDBC_URL} # pushes the flyway schema
#    username: ${BACKUP_AUTH_JDBC_USERNAME}
#    password: ${BACKUP_AUTH_JDBC_PASSWORD}
---
flyway:
  datasources:
    default:
      enabled: true
---
netty:
  default:
    allocator:
      max-order: 10