micronaut:
  application:
    name: auth
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - ${CORS_URL}
#  ssl:
#    enabled: true
#    build-self-signed: true
#  http:
#    client:
#      ssl:
#        enabled: true
#        build-self-signed: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
datasources:
  default:
    url: ${AUTH_JDBC_URL}
    username: ${AUTH_JDBC_USERNAME}
    password: ${AUTH_JDBC_PASSWORD}
    dialect: ${AUTH_JDBC_DIALECT}
flyway:
  datasources:
    default:
      enabled: true